import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
fs.mkdirSync('test-results',{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-unsafe-swiftshader','--use-angle=swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:900},locale:'en-US'});
const errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const check=(name,value)=>{assert.ok(value,name);checks.push(name);console.log('PASS',name);};
const state=()=>page.evaluate(()=>{const g=window.__game;return {running:g.running,time:g.time,hp:g.player.hp,alive:g.player.alive,score:g.player.score,deaths:g.player.deaths,ammo:g.weapon.ammo,reserve:g.weapon.reserve,weapon:g.weapon.config.id,slot:g.weapons.slot,locked:g.input.locked,position:g.player.position.toArray(),yaw:g.player.yaw,pitch:g.player.pitch,fov:g.camera.fov,screen:g.ui.screen};});
async function freeze(){await page.evaluate(()=>{const g=window.__game;window.__updates=g.ais.map(ai=>ai.update);g.ais.forEach(ai=>ai.update=()=>{});});}
async function fixture({part='body',range=8}={}){await page.evaluate(({part,range})=>{const g=window.__game,p=g.player,b=g.bots[0];p.position.set(-2,0,18);p.velocity.set(0,0,0);p.grounded=true;p.alive=true;p.hp=100;p.protectedUntil=0;p.yaw=0;p.pitch=Math.atan2((part==='head'?1.58:part==='legs'?.35:1.05)-1.65,range);p.recoil=0;g.bots.forEach((b,i)=>{b.position.set(60+i*2,0,70);b.velocity.set(0,0,0);b.protectedUntil=0;});b.position.set(-2,0,18-range);b.alive=true;b.hp=100;b.crouched=false;b.yaw=Math.PI;g.weapon.cooldown=0;g.weapon.heat=0;g.weapon.reloadLeft=0;g.weapon.cancelAttack();g.weapons.switchLeft=0;p.update(.001,g.input,g.map);g.camera.updateMatrixWorld(true);},{part,range});await page.waitForTimeout(60);}
async function unlock(){await page.evaluate(()=>document.exitPointerLock());await page.waitForTimeout(100);}
async function equip(id){await unlock();await page.locator('#pause [data-action="menu"]').click();await page.locator('#menu nav [data-action="loadout"]').click();await page.locator(`[data-weapon="${id}"]`).click();await page.locator('#dialog .primary').click();await page.locator('#play').click();await page.waitForTimeout(150);}
try{
  await page.goto('http://127.0.0.1:5173');await page.waitForFunction(()=>window.__game);await page.screenshot({path:'test-results/menu.png'});
  check('Main menu and PLAY render',await page.locator('#play').isVisible());
  await page.locator('#menu nav [data-action="loadout"]').click();check('Four primary loadout cards',await page.locator('.weapon-card').count()===4);await page.screenshot({path:'test-results/loadout.png'});await page.locator('#dialog .primary').click();
  await page.locator('#menu nav [data-action="settings"]').click();await page.locator('#dialog [data-setting="fov"]').fill('105');await page.locator('#dialog [data-setting="sensitivity"]').fill('1.25');await page.locator('#dialog [data-setting="quality"]').selectOption('low');await page.screenshot({path:'test-results/settings.png'});await page.locator('#dialog [data-action="close"]').last().click();
  await page.reload();await page.waitForFunction(()=>window.__game);check('Settings persist across reload',await page.evaluate(()=>window.__game.settings.data.fov===105&&window.__game.settings.data.sensitivity===1.25));
  await page.locator('#play').click();await page.waitForTimeout(300);check('PLAY starts FFA and locks mouse',(await state()).running&&(await state()).locked);check('Seven bots spawn',await page.evaluate(()=>window.__game.bots.length===7));
  await freeze();await fixture();const before=await state();await page.mouse.move(790,450);await page.waitForTimeout(70);check('Mouse look changes yaw',(await state()).yaw!==before.yaw);await fixture();
  await page.keyboard.down('KeyW');await page.waitForTimeout(500);await page.keyboard.up('KeyW');check('WASD changes world position',(await state()).position[2]<17);
  await page.keyboard.down('Space');await page.waitForTimeout(190);check('Jump lifts player',(await state()).position[1]>.4);await page.keyboard.up('Space');await page.waitForTimeout(800);
  await page.keyboard.down('ControlLeft');await page.waitForTimeout(150);check('Crouch lowers eye',await page.evaluate(()=>window.__game.player.crouched&&window.__game.player.eye<1.4));await page.keyboard.up('ControlLeft');await page.waitForTimeout(250);
  const movement=await page.evaluate(()=>{const g=window.__game,p=g.player;g.input.clear();p.position.set(-2,0,18);p.velocity.set(0,0,0);p.yaw=0;g.input.keys.add('KeyW');g.input.keys.add('ShiftLeft');g.input.keys.add('Space');let maxSpeed=0;for(let i=0;i<500;i++){p.update(1/120,g.input,g.map);maxSpeed=Math.max(maxSpeed,Math.hypot(p.velocity.x,p.velocity.z));}g.input.clear();p.position.set(-46,0,4);p.velocity.set(0,0,-10);for(let i=0;i<120;i++)g.map.move(p,1/120);const collision=p.position.z>=1.41;return {maxSpeed,collision};});
  check('Bunny hop stays under speed cap',movement.maxSpeed<=13.001&&movement.maxSpeed>9);check('Solid warehouse wall blocks movement',movement.collision);
  await fixture();await page.mouse.down();await page.mouse.up();await page.waitForTimeout(100);check('Rifle body hit applies 25 damage',await page.evaluate(()=>window.__game.bots[0].hp===75));
  await fixture({part:'head'});await page.mouse.down();await page.mouse.up();await page.waitForTimeout(100);check('Head hit applies 2x damage',await page.evaluate(()=>window.__game.bots[0].hp===50));
  await fixture({part:'legs'});await page.mouse.down();await page.mouse.up();await page.waitForTimeout(100);check('Leg hit applies 0.75x damage',await page.evaluate(()=>window.__game.bots[0].hp===81.25));
  await fixture({part:'head'});await page.mouse.down();await page.waitForTimeout(350);await page.mouse.up();check('Rifle kills bot and awards +1',await page.evaluate(()=>!window.__game.bots[0].alive&&window.__game.player.score===1));
  await page.screenshot({path:'test-results/kill.png'});check('Kill feed populated',await page.locator('#killfeed').innerText().then(t=>t.includes('EMBER')));await page.waitForTimeout(3250);check('Bot respawns after three seconds',await page.evaluate(()=>window.__game.bots[0].alive&&window.__game.bots[0].hp===100));
  const ammoBefore=await state();await page.keyboard.press('KeyR');await page.waitForTimeout(1950);const reloaded=await state();check('Reload conserves ammunition',reloaded.ammo===30&&reloaded.ammo+reloaded.reserve===ammoBefore.ammo+ammoBefore.reserve);
  await page.keyboard.press('KeyR');check('Full magazine cannot reload',await page.evaluate(()=>window.__game.weapon.reloadLeft===0));
  await page.keyboard.press('Digit2');await page.waitForTimeout(350);check('Slot 2 selects pistol',(await state()).weapon==='pistol');await fixture();await page.mouse.down();await page.waitForTimeout(650);await page.mouse.up();check('Pistol is semi automatic',(await state()).ammo===11);check('Pistol damages target',await page.evaluate(()=>window.__game.bots[0].hp===70));
  await page.keyboard.press('Digit3');await page.waitForTimeout(850);await fixture({range:1.8});await page.mouse.down();await page.mouse.up();await page.waitForTimeout(500);check('Knife light stab hits within melee range',await page.evaluate(()=>window.__game.bots[0].hp===55));
  check('Knife is melee only and never consumable',await page.evaluate(()=>{const g=window.__game;return g.weapons.slot===2&&g.weapon.config.id==='knife'&&g.weapon.ammo===1;}));
  await fixture({range:5});await page.mouse.down();await page.mouse.up();await page.waitForTimeout(500);check('Knife cannot hit distant target',await page.evaluate(()=>window.__game.bots[0].hp===100));
  await page.mouse.wheel(0,100);await page.waitForTimeout(350);check('Mouse wheel switches weapon',(await state()).weapon==='rifle');
  await page.keyboard.down('Tab');await page.waitForTimeout(150);check('Scoreboard lists 8 players',await page.locator('#scoreboard tbody tr').count()===8);await page.screenshot({path:'test-results/scoreboard.png'});await page.keyboard.up('Tab');
  await unlock();const paused=(await state()).time;await page.waitForTimeout(300);check('Pause freezes match',(await state()).time===paused);await page.locator('#pause [data-action="resume"]').click();await page.waitForTimeout(100);check('Resume restores pointer lock',(await state()).locked);
  await equip('smg');await fixture();await page.mouse.down();await page.waitForTimeout(300);await page.mouse.up();check('SMG selected and fires automatically',(await state()).weapon==='smg'&&(await state()).ammo<33);
  await equip('sniper');await fixture();await page.mouse.down({button:'right'});await page.waitForTimeout(400);check('Sniper scope changes FOV',(await state()).fov<26&&await page.locator('#scope').isVisible());await page.screenshot({path:'test-results/scope.png'});await page.mouse.down();await page.mouse.up();await page.waitForTimeout(100);check('Scoped sniper body shot kills',await page.evaluate(()=>!window.__game.bots[0].alive));await page.mouse.up({button:'right'});
  await equip('shotgun');await fixture({range:3});await page.mouse.down();await page.mouse.up();await page.waitForTimeout(100);check('Shotgun pellets kill at close range',await page.evaluate(()=>!window.__game.bots[0].alive));
  await equip('rifle');await page.evaluate(()=>{const g=window.__game;g.ais.forEach((ai,i)=>ai.update=window.__updates[i]);g.input.clear();g.player.position.set(-2,0,18);g.player.protectedUntil=0;g.bots[0].position.set(-2,0,9);g.ais[0].scanAt=0;g.ais[0].reactAt=0;g.ais[0].reset();g.faceCenter();window.__startPositions=g.bots.map(b=>b.position.clone());window.__sawPlayerDeath=false;window.__sawPlayerRespawn=false;});
  const aiReport=await page.evaluate(()=>{const g=window.__game;let states=new Set();for(let i=0;i<60*60;i++){g.tick(1/60);g.input.endFrame();g.ais.forEach(ai=>states.add(ai.bot.state));if(!g.player.alive)window.__sawPlayerDeath=true;if(window.__sawPlayerDeath&&g.player.alive)window.__sawPlayerRespawn=true;}return {states:[...states],moved:g.bots.map((b,i)=>b.position.distanceTo(window.__startPositions[i])),kills:g.bots.map(b=>b.kills),playerDeaths:g.player.deaths,died:window.__sawPlayerDeath,respawned:window.__sawPlayerRespawn,finite:g.actors.every(a=>[a.hp,...a.position.toArray(),...a.velocity.toArray()].every(Number.isFinite))};});
  console.log('AI REPORT',JSON.stringify(aiReport));check('All seven bots navigate',aiReport.moved.every(d=>d>2));check('Bots find enemies and shoot',aiReport.states.includes('Strafe')&&aiReport.kills.reduce((a,b)=>a+b,0)>0);check('Bot attacks kill player and player respawns',aiReport.died&&aiReport.respawned);check('Simulation contains no NaN or infinity',aiReport.finite);
  await page.screenshot({path:'test-results/gameplay.png'});
  await page.evaluate(()=>{const g=window.__game;while(!g.match.ended){g.tick(1/60);g.input.endFrame();}});await page.waitForTimeout(100);check('Full 300 second match reaches results',(await state()).screen==='results'&&await page.locator('#results').isVisible());check('Results include podium and 8 standings',await page.locator('#podium>div').count()===3&&await page.locator('#results tbody tr').count()===8);await page.screenshot({path:'test-results/results.png'});
  await page.waitForTimeout(6000);await page.locator('#results [data-action="play"]').click();await page.waitForTimeout(200);check('Play Again resets scores, ammo, time and starts match',await page.evaluate(()=>{const g=window.__game;return g.running&&g.match.remaining>299&&g.actors.every(a=>a.score===0&&a.hp===100)&&g.weapon.ammo===30;}));
  check('No browser console errors or exceptions',errors.length===0);
  fs.writeFileSync('test-results/report.json',JSON.stringify({passed:checks.length,checks,errors,aiReport},null,2));
}catch(e){await page.screenshot({path:'test-results/failure.png'});console.error('FAILED',e);console.error('BROWSER ERRORS',errors);console.error('STATE',await state(),await page.evaluate(()=>window.__game.input.lastLockError));fs.writeFileSync('test-results/report.json',JSON.stringify({checks,errors,failure:String(e)},null,2));process.exitCode=1;}finally{await browser.close();}



